export const BurguersKenzie = [
  {
    id: 1,
    name: "Hamburguer",
    category: "Sanduíches",
    price: 14,
    image: "https://i.imgur.com/Vng6VzV.png",
    quantity: 1,
  },
  {
    id: 2,
    name: "X-Burguer",
    category: "Sanduíches",
    price: 16,
    image: "https://i.imgur.com/soOUeeW.png",
    quantity: 1,
  },
  {
    id: 3,
    name: "Big Kenzie",
    category: "Sanduíches",
    price: 18,
    image: "https://i.imgur.com/eEzZzcF.png",
    quantity: 1,
  },
  {
    id: 4,
    name: "Fanta Guaraná",
    category: "Bebidas",
    price: 5,
    image: "https://i.imgur.com/YuIbfCi.png",
    quantity: 1,
  },
  {
    id: 5,
    name: "Coca-Cola",
    category: "Bebidas",
    price: 4.99,
    image: "https://i.imgur.com/KC2ihEN.png",
    quantity: 1,
  },
  {
    id: 6,
    name: "Milkshake Ovomaltine",
    category: "Bebidas",
    price: 4.99,
    image: "https://i.imgur.com/iNkD4Pq.png",
    quantity: 1,
  },
];
